spring:
  datasource:
    url: jdbc:mysql://192.168.33.25:3306/lib_acceso?useSSL=false
    username: root
    password: viewnext
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.33.25
  
logging:
  level:
    org.springframework.security: DEBUG