server:
  port: 8761
eureka:
  instance:
    hostname: 192.168.33.25
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/