security:
  sessions: NEVER
spring:
  datasource:
    url: jdbc:mysql://192.168.33.25/lib_catalogo?useSSL=false
    username: root
    password: viewnext
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties: 
      hibernate: 
        dialect:  org.hibernate.dialect.MySQL5Dialect
#Respeta el caso en las anotaciones de la entidad
    hibernate: 
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#No respeta el caso en las anotaciones de la entidad, por lo menos en Windows (no es sensible al caso)
#spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy        