security:
  sessions: ALWAYS
acceso:
  cliente-url: http://localhost:8083
spring:
  datasource:
    url: jdbc:mysql://192.168.33.25:3306/lib_acceso?useSSL=false
    username: root
    password: viewnext
    driver-class-name: com.mysql.jdbc.Driver
    
zuul:
  routes:
    inicio:
      path: /
      serviceId: servicio-ui
    servicio-ui:
      path: /ui/**
      sensitive-headers:
    servicio-cliente:
      path : /cliente/**
      stripPrefix: false
      sensitive-headers:
    servicio-catalogo: 
      path : /catalogo/**
      stripPrefix: false
    categoria:
      path : /categoria/**
      stripPrefix: false
      serviceId: servicio-catalogo
    servicio-busqueda:
      path: /busqueda/**
      stripPrefix: false
    servicio-carrito:
      path: /carrito/**
      stripPrefix: false
      sensitive-headers:
    servicio-admin: 
      path: /admin/**
      sensitive-headers:
logging:
  level:
    org.springframework: 
      security: DEBUG