spring:
  datasource:
    url: jdbc:mysql://192.168.33.25/lib_cliente?useSSL=false
    username: root
    password: viewnext
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties: 
      hibernate: 
        dialect:  org.hibernate.dialect.MySQL5Dialect
    hibernate: 
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
