server:
  port: ${PORT:8080}
security:
  sessions: NEVER
spring:
  redis:
    host: 192.168.33.25
logging:
  level:
    org.springframework: 
      security: DEBUG
      session: TRACE
      data.redis : DEBUG     