security:
  sessions: ALWAYS
spring:
  datasource:
    url: jdbc:mysql://192.168.33.25:3306/lib_acceso?useSSL=false
    username: root
    password: viewnext
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.33.25  
zuul:
  routes:
    inicio:
      path: /
      url: http://localhost:8084/
    ui:
      url: http://localhost:8084
      sensitive-headers:
    cliente:
      path : /cliente/**
      url: http://localhost:8083/cliente
      sensitive-headers:
    catalogo: 
      path : /catalogo/**
      url : http://localhost:8082/catalogo
    categoria:
      path : /categoria/**
      url : http://localhost:8082/categoria
    busqueda:
      path: /busqueda/**
      url : http://localhost:8081/busqueda
    carrito:
      path: /carrito/**
      url: http://localhost:8085/carrito
      sensitive-headers:
      