CREATE DATABASE lib_catalogo;

USE lib_catalogo;

CREATE TABLE CAT_LIBRO(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITULO VARCHAR(100) NOT NULL,
	DESCRIPCION VARCHAR(250),
	PRECIO DECIMAL(6,2),
	ANNO SMALLINT,
	ISBN VARCHAR(13),
	CATEGORIA INTEGER);
CREATE TABLE CAT_CATEGORIA(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DESCRIPCION VARCHAR(50) NOT NULL);
CREATE TABLE CAT_AUTORES(
	ID_LIBRO INTEGER NOT NULL,
	NOMBRE VARCHAR(50),
	PRIMARY KEY(ID_LIBRO,NOMBRE));

ALTER TABLE CAT_LIBRO ADD FOREIGN KEY(CATEGORIA) REFERENCES CAT_CATEGORIA(ID);
ALTER TABLE CAT_AUTORES ADD FOREIGN KEY(ID_LIBRO) REFERENCES CAT_LIBRO(ID);

SET NAMES utf8;

INSERT INTO CAT_CATEGORIA (DESCRIPCION) VALUES('Literatura y ficción');
INSERT INTO CAT_CATEGORIA (DESCRIPCION) VALUES('Tecnología e ingienería');

INSERT INTO CAT_LIBRO (TITULO,DESCRIPCION,PRECIO,ANNO,ISBN,CATEGORIA) VALUES('EL MOZARABE','Cuando en 939 el emir Abd-al-Rahman III se erige como califa, la España musulmana comienza una etapa de esplendor inigualable cuyo estandarte será su capital, Córdoba',19.00,2011,'546564464848',1);
INSERT INTO CAT_LIBRO (TITULO,DESCRIPCION,PRECIO,ANNO,ISBN,CATEGORIA) VALUES('Don Quijote de la Mancha. Primera parte: Versión original abreviada',NULL,3.31,0,'8480637471',1);
INSERT INTO CAT_LIBRO (TITULO,DESCRIPCION,PRECIO,ANNO,ISBN,CATEGORIA) VALUES('Física Teórica. Mecánica','Este primer tomo del Curso de Física teórica está dedicado naturalmente a los fundamentos del tema, es decir a la Mecánica clásica newtoniana y contiene los problemas fundamentales de la Mecánica teórica:',26.19,1970,'8429140816',2);
INSERT INTO CAT_LIBRO (TITULO,DESCRIPCION,PRECIO,ANNO,ISBN,CATEGORIA) VALUES('Electrónica digital y microprocesadores',NULL,15.65,1993,'8487840337',2);

INSERT INTO CAT_AUTORES (ID_LIBRO, NOMBRE) VALUES(1,'Jesus Sanchez Adalid');
INSERT INTO CAT_AUTORES (ID_LIBRO, NOMBRE) VALUES(2,'Miguel de Cervantes');
INSERT INTO CAT_AUTORES (ID_LIBRO, NOMBRE) VALUES(3,'L. D. Landau');
INSERT INTO CAT_AUTORES (ID_LIBRO, NOMBRE) VALUES(4,'Eduardo Santamaría');
