server:
  port: ${PORT:8080}
  
spring:
  datasource:
    url: jdbc:mysql://192.168.33.25:3306/lib_catalogo?useSSL=false
    password: viewnext
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        strategy: org.hibernate.cfg.EJB3NamingStrategy