server:
  port: ${PORT:8080}
security:
  sessions: NEVER  
spring:
  datasource:
    url: jdbc:mysql://192.168.33.25:3306/lib_cliente?useSSL=false
    password: viewnext
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    host: 192.168.33.25
logging:
  level:
    org.springframework: 
      security: DEBUG
      session: TRACE    